import Head from "next/head";
import Image from "next/image";
import Card from "../components/Card";
import styles from "../styles/Home.module.css";

export default function Home({ data }) {
  return (
    <>
      <div className={styles.body}>
        <Head>
          <title>Movies</title>
          <meta name="description" content="Generated by create next app" />
          <link rel="icon" href="/favicon.ico" />
        </Head>
        <div className={styles.header}>See what&apos;'s trending today!</div>
        <div className={styles.container}>
          <main className={styles.main}>
            {data.results.map((movie) => (
              <Card
                key={movie.id}
                title={movie.title}
                poster={`https://image.tmdb.org/t/p/w1280${movie.poster_path}`}
                rating={movie.vote_average}
                status={
                  movie.vote_average >= 8
                    ? "darkgreen"
                    : movie.vote_average >= 5
                    ? "orange"
                    : "red"
                }
                overview={movie.overview}
              />
            ))}
          </main>
        </div>
      </div>
    </>
  );
}

export async function getStaticProps() {
  const res = await fetch(
    "https://api.themoviedb.org/3/discover/movie?sort_by=popularity.desc&api_key=af183e2660d4b07b6f357fdc745bf737"
  );
  const data = await res.json();

  return {
    props: { data },
  };
}
